"""
Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import time
import math
# res = 0
# n = 500
# count = 0
# count_lis = []
# i = 1
# while len(count_lis) == 0:
#     count = 0
#     res += i
#
#     for j in range(1, int(res**0.5)+1):
#         if res == 1:
#             count += 1
#         elif res % j == 0:
#             count += 2
#     if count >= n:
#         count_lis.append([res, count])
#
#     i += 1
#
# print(count_lis)
# print("This program took: " + str(time.process_time() * 1000) + "ms.")


# Same idea with optimization
def numoffactors(n):
    root = math.sqrt(n)
    square = int(root)
    count = -1 if square == root else 0

    for element in range (1, square + 1):
        if not n % element: count += 2
    return count

triangle = 1
index = 1
while numoffactors(triangle) < 500:
    index += 1
    triangle += index

print(triangle)
print("This program took: " + str(time.process_time() * 1000) + "ms.")

